liberapay: marcpartensky
patreon: marcpartensky
github: marcpartensky
paypal: marcpartensky
buymeacoffee: marcpartensky
# custom:
  # - monero:43J2XmRtjDPRLD35UsYGH2AZamFBQz7dt4VdvZXVm3SuadTrvcoXUXBRUNHqukFte23Q5TWXqhbwaLJJgoVQzzbe2AJDANQ
